import { useState } from "react";
import { type ConnectionProfile, saveActive, validateAnon } from "../lib/connectionProfile";
import { testConnection } from "../lib/streamClient";
interface Props { onReady: () => void; onBack: () => void; }
export function AnonSetup({ onReady, onBack }: Props) {
  const [form, setForm] = useState<ConnectionProfile>({ label:"Agent (anonymous)", kind:"agent", endpoint:"", apiVersion:"v1", authMode:"entra-app", tenantId:"", clientId:"", clientSecret:"", scope:"https://ai.azure.com/.default" });
  const [errors, setErrors] = useState<string[]>([]); const [testMsg, setTestMsg] = useState("");
  const set = (k: keyof ConnectionProfile, v: string) => setForm((f) => ({ ...f, [k]: v }));
  const onTest = async () => { const e = validateAnon(form); setErrors(e); if (e.length) return; setTestMsg("Testing…"); const r = await testConnection(form); setTestMsg(r.ok ? "✅ Connection valid" : `❌ ${r.error}`); };
  const onSubmit = () => { const e = validateAnon(form); setErrors(e); if (e.length) return; saveActive(form); onReady(); };
  return (<div className="setup-screen"><div className="setup-card"><button className="btn-link setup-back" onClick={onBack}>← Back</button><h2>🕶️ Anonymous mode · Agent</h2><p className="hint">Enter the details provided by the administrator. Nothing is stored persistently: it lives only in this tab.</p><label>Agent endpoint (full URL)</label><input value={form.endpoint} onChange={(e) => set("endpoint", e.target.value)} placeholder="https://<res>.services.ai.azure.com/api/projects/<proj>/agents/<Agent>/endpoint/protocols/openai/responses" /><label>api-version</label><input value={form.apiVersion} onChange={(e) => set("apiVersion", e.target.value)} placeholder="v1" /><p className="mode-note warn">⚠️ Service principal: the secret is forwarded over HTTPS and <b>not persisted</b>. All anonymous users act with this app's identity.</p><div className="row"><div><label>Tenant ID</label><input value={form.tenantId} onChange={(e) => set("tenantId", e.target.value)} /></div><div><label>Client ID</label><input value={form.clientId} onChange={(e) => set("clientId", e.target.value)} /></div></div><label>Client secret</label><input type="password" value={form.clientSecret} onChange={(e) => set("clientSecret", e.target.value)} placeholder="Service principal secret" /><label>Scope</label><input value={form.scope} onChange={(e) => set("scope", e.target.value)} />{errors.length > 0 && <ul className="errors">{errors.map((e) => <li key={e}>{e}</li>)}</ul>}{testMsg && <p className="test-msg">{testMsg}</p>}<div className="modal-actions"><button className="btn-secondary" onClick={onTest}>Test connection</button><div style={{ flex: 1 }} /><button className="btn-primary" onClick={onSubmit}>Enter chat</button></div></div></div>);
}
